//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_CRUD_Operation.DB_Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVENGER
    {
        public int SrNo { get; set; }
        public string ANAME { get; set; }
        public string AEMAILID { get; set; }
        public string APASSWORD { get; set; }
        public string CODE { get; set; }
    }
}
