//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_CRUD_Operation.DB_Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class NDeveloper
    {
        public int DID { get; set; }
        public string DNAME { get; set; }
        public string DEMAILID { get; set; }
        public string DNUMBER { get; set; }
        public string DTECHNOLOGY { get; set; }
        public string DESIGNATION { get; set; }
    }
}
